### ISSUE TITLE
Mistake in dist/index.js

### ISSUE THREAD

**Issue by DiaxManPl** [SerenModz21/paste.gg#3]
Hi. I'm using your package and i found a mistake. In file `dist/index.js` in line 37 and 61, after `auth` and `key` cannot be `?`. Sorry for my bad english.

**Comment by SerenModz21** [comment]
Hello. First, may I know what version of node you're using?

**Comment by SerenModz21** [comment]
With you not being able to use `?.`, I can see that you use a node version below v14. I have changed my TypeScript compiler options to work with the older node versions.

I have pushed this fix to NPM as version 1.0.2 which you can now download. I hope this fixes the issue you are having. If you have any more issues, feel free to let me know.

**Comment by DiaxManPl** [comment]
Sorry, I didn't checked this in other node versions. Thanks for fixing this error.

**Comment by SerenModz21** [comment]
It's ok. Thank you for reporting this to me. Before I close the issue, did the fix I pushed fixed the issue you was having?

**Comment by DiaxManPl** [comment]
Yes, you fixed.

**Comment by SerenModz21** [comment]
> Yes, you fixed.

That's great news. Have a great day/evening 😃
